packages:
  - packages/*

catalog:
  "@ayingott/eslint-config": ^2.0.6
  "@types/node": ^24.3.3
  bumpp: ^10.2.3
  eslint: ^9.35.0
  lint-staged: ^16.1.6
  prettier: ^3.6.2
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-tailwindcss: ^0.6.14
  simple-git-hooks: ^2.13.1
  taze: ^19.6.0
  tsdown: ^0.15.1
  typescript: ^5.9.2

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - simple-git-hooks
  - unrs-resolver
