packages:
  - packages/*

catalog:
  "@ayingott/eslint-config": ^2.0.4
  "@types/node": ^24.0.0
  bumpp: ^10.1.1
  eslint: ^9.28.0
  lint-staged: ^16.1.0
  prettier: ^3.5.3
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-tailwindcss: ^0.6.12
  simple-git-hooks: ^2.13.0
  taze: ^19.1.0
  tsdown: ^0.12.7
  typescript: ^5.8.3

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - simple-git-hooks
  - unrs-resolver
