packages:
  - packages/*

catalog:
  "@ayingott/eslint-config": ^2.0.2
  "@types/node": ^22.15.3
  bumpp: ^10.1.0
  eslint: ^9.25.1
  lint-staged: ^15.5.1
  prettier: ^3.5.3
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-tailwindcss: ^0.6.11
  simple-git-hooks: ^2.13.0
  taze: ^19.0.4
  tsdown: ^0.10.1
  typescript: ^5.8.3

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - simple-git-hooks
  - unrs-resolver
